version: "3.8"

services:
  db:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - db_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
      - 8001:8001
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
